const images = {
    logo: require('./logo.png'),
    platform1: require('./platform1.png'),
    grass_main: require('./grass_main.png'),
    generic_deathtiles: require('./generic_deathtiles.png'),
    player: require('./player.png'),
    cursor: require('./cursor.png'),
    hook: require('./hook.png'),
    flag_start: require('./flagStart.png'),
    flag_end: require('./flagEnd.png'),
    bg_cloud1: require('./bg_cloud1.png'),
    bg_cloud2: require('./bg_cloud2.png'),
    bg_cloud3: require('./bg_cloud3.png'),
    backgroundMenu: require('./backgroundMenu.png'),
    startGameButton: require('./startGameButton.png'),
    settingsButton: require('./settingsButton.png'),
    buttonA: require('./buttonA.png'),
    buttonD: require('./buttonD.png'),
    buttonSpace: require('./buttonSpace.png'),
    buttonMouse: require('./buttonMouse.png'),
    buttonEsc: require('./buttonEsc.png'),
    backButton: require('./backButton.png'),
    buttonMusicOn: require('./buttonMusicOn.png'),
    buttonMucicOff: require('./buttonMusicOff.png'),
    favicon: require('./site-icon.ico'),
}

export { images };